apiVersion : apps/v1
kind: Deployment
metadata:
  name: azure-pipeline 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-pipeline
  template:
    metadata:
      labels:
        app: azure-pipeline 
    spec:
      containers:
        - name: azure-pipeline 
          image: onlyregistryhere.azurecr.io/azure-pipeline
          ports:
          - containerPort: 8000